// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Struggle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("api.Models.JournalEntryStruggle", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<int>("StruggleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLinked")
                        .HasColumnType("datetime2");

                    b.HasKey("JournalEntryId", "StruggleId");

                    b.HasIndex("StruggleId");

                    b.ToTable("JournalEntryStruggles");
                });

            modelBuilder.Entity("api.Models.Scripture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scriptures");
                });

            modelBuilder.Entity("api.Models.Struggle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Root")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Struggles");
                });

            modelBuilder.Entity("api.Models.StruggleScripture", b =>
                {
                    b.Property<int>("StruggleId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLinked")
                        .HasColumnType("datetime2");

                    b.HasKey("StruggleId", "ScriptureId");

                    b.HasIndex("ScriptureId");

                    b.ToTable("StruggleScriptures");
                });

            modelBuilder.Entity("api.Models.JournalEntryStruggle", b =>
                {
                    b.HasOne("api.Models.JournalEntry", "JournalEntry")
                        .WithMany("JournalEntryStruggles")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Struggle", "Struggle")
                        .WithMany("JournalEntryStruggles")
                        .HasForeignKey("StruggleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");

                    b.Navigation("Struggle");
                });

            modelBuilder.Entity("api.Models.StruggleScripture", b =>
                {
                    b.HasOne("api.Models.Scripture", "Scripture")
                        .WithMany("StruggleScriptures")
                        .HasForeignKey("ScriptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Struggle", "Struggle")
                        .WithMany("StruggleScriptures")
                        .HasForeignKey("StruggleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scripture");

                    b.Navigation("Struggle");
                });

            modelBuilder.Entity("api.Models.JournalEntry", b =>
                {
                    b.Navigation("JournalEntryStruggles");
                });

            modelBuilder.Entity("api.Models.Scripture", b =>
                {
                    b.Navigation("StruggleScriptures");
                });

            modelBuilder.Entity("api.Models.Struggle", b =>
                {
                    b.Navigation("JournalEntryStruggles");

                    b.Navigation("StruggleScriptures");
                });
#pragma warning restore 612, 618
        }
    }
}
